version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - WEB_HOOK_URL=http://backend:3000/webhook
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./problems:/app/problems
    depends_on:
      - redis
      - backend

  celery_beat:
    build:
      context: ./worker
      dockerfile: Dockerfile
    command: celery -A tasks beat --loglevel=info
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis

  flower:
    build:
      context: ./worker
      dockerfile: Dockerfile
    command: celery -A tasks flower
    ports:
      - "5555:5555"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
      - celery_worker
